image: registry.aditsystems.de/as-crm/portal:latest
variables:
  SONAR_URL: https://sonarqube.aditsystems.de
  SONAR_USER_HOME: ${CI_PROJECT_DIR}/${CACHE_DIR}/sonar
  CI_BUILD_REF: ${CI_COMMIT_SHA}
  CI_BUILD_REF_NAME: ${CI_COMMIT_REF_NAME}
  SONAR_GITLAB_PROJECT_ID: ${CI_PROJECT_URL}
  VERBOSITY: 2

stages:
  - build

cache:
  paths:
  - ~/.cache/pip/

build:
  image: 1drop/php-72-docker-utils
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - nova
  cache:
    policy: pull