---
version: '3'

services:
    redis:
        image: redis:alpine

    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=nice_marmot
            - POSTGRES_USER=runner
            - POSTGRES_PASSWORD=password

    web:
        build: .
        command: "python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SETTINGS_MODULE=Portal.docker
            - PYTHONUNBUFFERED=1
            - "DB_NAME=nice_marmot"
            - "DB_USER=runner"
            - "DB_PASS=password"
            - "DB_HOST=db"
            - "DB_PORT=5432"
