---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "appname" . }}-migrate"
  annotations:
    meta.helm.sh/release-name: "{{ template "appname" . }}"
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
  labels:
    app: "{{ template "appname" . }}"
spec:
  template:
    metadata:
      labels:
        app: "{{ template "appname" . }}"
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: "{{ template "appname" . }}-deploy-secret"
      containers:
        - name: "{{ template "appname" . }}-app"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: "{{ template "appname" . }}"
            - secretRef:
                name: "{{ template "appname" . }}-secret"
          ports:
            - name: http
              containerPort: 8000
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 32Mi
