---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "appname" . }}-secret"
type: Opaque
data:
  DB_NAME: {{ .Values.db.name | b64enc | quote }}
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASS: {{ .Values.db.pass | b64enc | quote }}
  DB_HOST: {{ .Values.db.host | b64enc | quote }}
