---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "appname" . }}"
  labels:
    app: "{{ template "appname" . }}"
spec:
  replicas: {{ .Values.portal.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "{{ template "appname" . }}"
  template:
    metadata:
      labels:
        app: "{{ template "appname" . }}"
        date: "{{ now | unixEpoch }}"
      annotations:
        prometheus.io/scheme : 'http'
        prometheus.io/path: /metrics
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      imagePullSecrets:
        - name: "{{ template "appname" . }}-deploy-secret"
      containers:
        - name: "{{ template "appname" . }}-app"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          envFrom:
            - configMapRef:
                name: "{{ template "appname" . }}"
            - secretRef:
                name: "{{ template "appname" . }}-secret"
          resources:
{{ toYaml .Values.portal.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 8000
