---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  POSTGRES_USER: {{ .Values.db.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.pass | b64enc | quote }}
type: Opaque
