---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-claim
    labels:
        app: postgres
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.db.storage | quote }}
    storageClassName: {{ .Values.storageClassName }}
