---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
      annotations:
        prometheus.io/scheme : 'http'
        prometheus.io/path: /metrics
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0