# Generated by Django 4.0.1 on 2022-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SepaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('sort_code', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
            ],
        ),
    ]
