apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-node-exporter
    jobLabel: node-exporter
    release: prometheus
  annotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  name: prometheus-prometheus-node-exporter
  namespace: test1asservertestnet
spec:
  ports:
    - name: prometheus-prometheus-node-exporter
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/release-name: prometheus
